### ISSUE TITLE
Something wrong with pagination.

### ISSUE THREAD

**Issue by rhnkyr** [manomintis/adonis-api-resources#1]
Hi @manomintis 

thanks for this package. Does this package supports pagination? Apparently in my project resource with pagination won't work.

**Comment by manomintis** [comment]
Hi @rhnkyr , actually it does not, unless it would somehow work on itself by miracle, it should not support pagination at this moment. This was the very first and primitive version of this package. The point was for it to appear in its basic form, as simple as it can be. However, I'm going to face the same issue very soon in my project, and I will need this package to support pagination. So I'm going to upgrade it and release a new version soon.

**Comment by rhnkyr** [comment]
Hi @manomintis thanks for swift reply! Any foreseen date to release this feature?

**Comment by manomintis** [comment]
@rhnkyr I can't say a date but we're talking maybe even about nearest few weeks. As soon as I finish a few things I'm working on at the moment, I will then have to use this package with pagination. So I will have to start with upgrading it, probably.

**Comment by manomintis** [comment]
@rhnkyr Pagination is now supported, please upgrade the package.
